### ISSUE TITLE
Help in uploading casbin model via database

### ISSUE THREAD

**Issue by afidegnum** [casbin/chi-authz#2]
How do load casbin model via database? i m using postgres
also how do i implement authentication features? i.e, login/out/registration etc ... 
is this project still active?

**Comment by hsluoyz** [comment]
If you don't want to load a model from ``.conf`` file. You can load it from Go string or code. See: https://casbin.org/docs/en/model-storage

I don't see a concrete need to load model from DB. Because the model is just a text or string, which should not be modified at run-time. If you really need to do this, you can populate the model instance from DB data by yourself like:

```go
m := casbin.NewModel()
m.AddDef("r", "r", "sub, obj, act")
m.AddDef("p", "p", "sub, obj, act")
m.AddDef("g", "g", "_, _")
m.AddDef("e", "e", "some(where (p.eft == allow))")
m.AddDef("m", "m", "g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act")
```

Casbin is under active development. And of course is also this project (Chi's middleware). Please contact us if you have further issues.

**Comment by afidegnum** [comment]
thanks for the prompt response, i have been following casbin for some time now I believe it could be the best solution for RBAC and ABAC among others... 

Let me follow your directives and see what comes out.

**Comment by hsluoyz** [comment]
Thanks for the comment :)

**Comment by hsluoyz** [comment]
Closed as stale.
